### PR TITLE
wptserve: Add capability to add url-directory mappings

### PR DESCRIPTION
**Pull request by tkent-google**
Add "aliases" dict to a config json file. It looks like:

    "aliases" : {
        "/resources/testharnessreport.js" : "/Users/tkent/blink/LayoutTests/resources",
        "/wpt_automation/" : "/Users/tkent/blink/LayoutTests/imported/wpt_automation"
    },

This feature is useful to override files in web-platform-tests or to inject
additional resources. For example, browser vendor can replace its own
testharnessreport.js without modifying web-platform-tests checkout.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/128)

### CODE REVIEW

**Comment by gsnedders** [comment]
Code LGTM, but I want to wait for feedback on the feature from @jgraham prior to merging.

**Comment by tkent-google** [comment]
@jgraham , what do you think?

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[serve/serve.py, line 160 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/128#-KUrftXk22GuXxxkhW60:-KUrftXk22GuXxxkhW61:b803tol) ([raw file](https://github.com/w3c/wpt-tools/blob/f917dd270363edbe8cb2dff843b71d9ee4fff1b5/serve/serve.py#L160)):*
> ```Python
>         assert file_url.startswith("/")
>         url_base = file_url[0:file_url.rfind("/") + 1]
>         self.mountpoint_routes[file_url] = \
> ```

Avoid line continuation characters if possible, please.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/128)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/128)*

**Comment by jgraham** [comment]
Sure that seems like a reasonable idea. Just one fixup.

**Comment by tkent-google** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[serve/serve.py, line 160 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/128#-KUrftXk22GuXxxkhW60:-KUszdzlePd1T-jAHnUJ:b-6rar3m) ([raw file](https://github.com/w3c/wpt-tools/blob/f917dd270363edbe8cb2dff843b71d9ee4fff1b5/serve/serve.py#L160)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Avoid line continuation characters if possible, please.
</details>
Done.
I didn't find something like a Python style guide in WPT.  Don't we have column limit?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/128)*

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[serve/serve.py, line 160 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/128#-KUrftXk22GuXxxkhW60:-KUurUVo-LyDYs6w5zwF:b9t5tsf) ([raw file](https://github.com/w3c/wpt-tools/blob/f917dd270363edbe8cb2dff843b71d9ee4fff1b5/serve/serve.py#L160)):*
<details><summary><i>Previously, tkent-google (TAMURA, Kent) wrote…</i></summary>
> Done.
> I didn't find something like a Python style guide in WPT.  Don't we have column limit?
> 
</details>
So far the style guide has been quite whimsical in the sense that it's based on my whims ;) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/128)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/128)*

**Pull request merged**
