### PR TITLE
support multiple paths in runner, separated by comma or whitespace

### PR DESCRIPTION
**Pull request by hrj**

### CODE REVIEW

**Comment by jgraham** [comment]
Reviewed on critic

**Comment by kristijanburnik** [comment]
@hrj 

Any chance you could squash and land this today? 

I was hoping to add regex support after this is in. :-)

**Comment by hrj** [comment]
@kristijanburnik I don't have commit rights ... yet :smile:

@jgraham Do you want me to squash / rebase this?

**Comment by kristijanburnik** [comment]
Yeah, I didn't mean merge by yourself. :-)  

I think @jgraham already mentioned you should squash it. Usually it's a "requirement" before merge. :)

**Comment by hrj** [comment]
Oh, sorry. I didn't notice the last few review comments by @jgraham. Will change regexp and squash.

**Comment by hrj** [comment]
superseded by #25

**Pull request closed without merging**
