### PR TITLE
Add test count

### PR DESCRIPTION
**Pull request by halindrome**
This is a simple change to show how many tests are matching the criteria specified.

Basically I think this is a first step in helping people to see if they are getting the tests they expect.

The next step should be to show the list of identified tests as a table that then gets filled in as the tests are run.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/75)

### CODE REVIEW

**Comment by maxpassion** [comment]
Is there any example for  the criteria?

**Comment by halindrome** [comment]
In runner you can specify patterns to match against the tests so runner knows what to run.  

So right now, for example, if you put in no criteria it would display this:

screenshot 2016-06-11 at 13 53 50

And if you then selected only reftests in folder /2dcontext it would display:

screenshot 2016-06-11 at 13 54 22

Does that help?

**Comment by halindrome** [comment]
@maxpassion or @jgraham  r?

**Comment by jgraham** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[runner/runner.js, line 482 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7wJxtmQ1vJmpX5l8_:-KN7wJxuPwkLpE9pphkt:-628021233) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L482)):*
> ```JavaScript
>     this.set_start();
>     this.set_counts();
>     this.recount_inputs = Array.prototype.slice.call(
> ```

Seems like it could be vaugely more understandable to remove the classes and say that this is `Array.prototype.concat.call(this.type_checkboxes), [document.getElementById("use_regex")])`

---

*[runner/runner.js, line 484 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7wqOuelHK_LrXOYJE:-KN7wqOuelHK_LrXOYJF:-1635602956) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L484)):*
> ```JavaScript
>     this.recount_inputs = Array.prototype.slice.call(
>         this.elem.querySelectorAll("input.recount"));
>     this.recount_inputs.forEach(function(elem) {
> ```

I would prefer that this move up to before `this.runner = runner;`

---

*[runner/runner.js, line 546 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7x1ACpK88HmKV9HPN:-KN7x1ACpK88HmKV9HPO:715353520) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L546)):*
> ```JavaScript
>         if (this.runner.manifest_loading) {
>             setTimeout(function() {
>                 this.set_counts();}.bind(this), 1000);
> ```

newline after `;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/75)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/75)*

**Comment by halindrome** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[runner/runner.js, line 482 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7wJxtmQ1vJmpX5l8_:-KN8l9nBWV-K29zmsVrk:1942723009) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L482)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Seems like it could be vaugely more understandable to remove the classes and say that this is `Array.prototype.concat.call(this.type_checkboxes), [document.getElementById("use_regex")])`
</details>
actually there was no reason for the recount class nor the separate loop.  There are event listeners added up above.  I moved it there.

---

*[runner/runner.js, line 484 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7wqOuelHK_LrXOYJE:-KN8lULUNUycuYWq-ZHN:1727763564) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L484)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I would prefer that this move up to before `this.runner = runner;`
</details>
I removed it altogether; moving it into the loop above that was already adding listeners.

---

*[runner/runner.js, line 546 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7x1ACpK88HmKV9HPN:-KN8ltWN45Ewr_OoYMvH:1758359711) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L546)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> newline after `;`
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/75)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/index.html, line 48 \[r2\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN9010rtzcG210-lNdF:-KN9010sN9NY96NXl4pk:1535867013) ([raw file](https://github.com/w3c/wpt-tools/blob/95e216b87ce3d4aaa7716a63d467d513a849758f/runner/index.html#L48)):*
> ```HTML
>           <label for="path" class="col-sm-3 control-label">Run tests under path</label>
>           <div class="col-sm-9">
>             <input value="/" id='path' class='recount path form-control' disabled>
> ```

Some `class=recount` remains.

---

*[runner/runner.js, line 546 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7x1ACpK88HmKV9HPN:-KN9-uRuFyfsNUdk6AUJ:-434375877) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L546)):*
<details><summary><i>Previously, halindrome (Shane McCarron) wrote…</i></summary>
> Fixed.
</details>
Seems like you forgot this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/75)*

**Comment by halindrome** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/index.html, line 48 \[r2\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN9010rtzcG210-lNdF:-KN92v6ft89uK-uq6djj:-1301830395) ([raw file](https://github.com/w3c/wpt-tools/blob/95e216b87ce3d4aaa7716a63d467d513a849758f/runner/index.html#L48)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Some `class=recount` remains.
</details>
uggh - that's what happens when you don't write out the file!

---

*[runner/runner.js, line 546 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/75#-KN7x1ACpK88HmKV9HPN:-KN931j9nVnssqtKaYvT:322779625) ([raw file](https://github.com/w3c/wpt-tools/blob/998e48ea6a029fbfbf9c252525ce57e56664d2fa/runner/runner.js#L546)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Seems like you forgot this change.
</details>
Maybe I don't know what you wanted....   oh!  you wanted me to ADD a new line.  duh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/75)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/75)*

**Pull request merged**
