### PR TITLE
Fixed runner to handle references

### PR DESCRIPTION
**Pull request by halindrome**
The format of the manifest had changed.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/67)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[runner/runner.js, line 119 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH0b2cQ5pJi1AC3QFKV:-KH0b2cRoIHZK8brvz3A:1017500845) ([raw file](https://github.com/w3c/wpt-tools/blob/abde525262acdf6e259bcd9e5faba68a678ef22b/runner/runner.js#L119)):*
This is technically wrong, but better than nothing. The semantics here changed so that any one of the references is allowed to match, and references may themselves have references, which must also match (or mismatch). Obviously adding this to the runner is much more work and it's not a common feature, but it might be nice to have a warning or something when a test has > 1 possible reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by sideshowbarker** [comment]
*[runner/runner.js, line 119 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH0b2cQ5pJi1AC3QFKV:-KH0dSMeWOhu8QjqVWU0:-2060658171) ([raw file](https://github.com/w3c/wpt-tools/blob/abde525262acdf6e259bcd9e5faba68a678ef22b/runner/runner.js#L119)):*
I think emitting a warning should be sufficient for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
I will add a warning when there are more than 1 references.

**Comment by sideshowbarker** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/runner.js, line 60 \[r2\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH2yNHXVewRh08bhBZH:-KH2yNHXVewRh08bhBZI:-1024906611) ([raw file](https://github.com/w3c/wpt-tools/blob/5adbbda1559a8fdc450946e6b5fffe262eea7a4c/runner/runner.js#L60)):*
Code-reviewed the change for the `local_changes` case and it looks right but did not test it. @jgraham should confirm.

---

*[runner/runner.js, line 427 \[r2\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH3AdIJtwA-WFexb9B4:-KH3AdIJtwA-WFexb9B5:2025298137) ([raw file](https://github.com/w3c/wpt-tools/blob/5adbbda1559a8fdc450946e6b5fffe262eea7a4c/runner/runner.js#L427)):*
Code-reviewed this and tested and confirmed that it works, but the warning is extremely easy to miss—because it is not styled in any way. Could you please consider adding, say, a (yellow?) background color to it, and/or a border, making it bold, or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by sideshowbarker** [comment]
@halindrome if you don’t want to have to hassle with styling the warning, just let me know and I can do it post-merge in a follow-up PR

**Comment by halindrome** [comment]
No - I can do it in runner.css @sideshowbarker

**Comment by halindrome** [comment]
As an aside - when the system is in reftest mode the dialog for manual / reftests covers the stop / pause buttons.  And since the dialog is not draggable there is no way to select those buttons.  I also wonder about the a11y of runner - but I have not really looked at that yet.

**Comment by jgraham** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[runner/runner.js, line 427 \[r2\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH3AdIJtwA-WFexb9B4:-KHK_cAJOtNW6YKV_yMc:1432341901) ([raw file](https://github.com/w3c/wpt-tools/blob/5adbbda1559a8fdc450946e6b5fffe262eea7a4c/runner/runner.js#L427)):*
<details><summary><i>Previously, sideshowbarker (Michael[tm] Smith) wrote…</i></summary>
> Code-reviewed this and tested and confirmed that it works, but the warning is extremely easy to miss—because it is not styled in any way. Could you please consider adding, say, a (yellow?) background color to it, and/or a border, making it bold, or something?</details>
Also, mention that we are only presenting the first.

---

*[runner/runner.js, line 53 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZ9ol6SUzj99vPmFb:-KHKZ9omv9pzRVx1K3xP:-473090924) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L53)):*
> ```JavaScript
>         var ret = [] ;
>         if (this.data.items.hasOwnProperty(type)) {
>             ret = this.data.items[type].slice(0) ;
> ```

`var`

---

*[runner/runner.js, line 62 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZlxJ1VhVl_55hyu0:-KHKZlxJ1VhVl_55hyu1:1980944982) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L62)):*
> ```JavaScript
>         if (this.data.hasOwnProperty("local_changes") && this.data.local_changes.items.hasOwnProperty(type)) {
>             Object.keys(this.data.local_changes.items[type]).forEach(function(ref) {
>                 ret.push(this.data.local_changes.items[type][ref][0]) ;
> ```

This `[0]` isn't really right; it should be all items (a single test file can have multiple variants that contribute different tests). Also you need to consider deleted items and the fact that reftests can change what their reference is, or whatever.

Unfortunately the best way to do this is probably to look at how the python code works and emulate that behaviour.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[runner/runner.js, line 119 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH0b2cQ5pJi1AC3QFKV:-KHKdMiW1tezFVFDlb4z:-499146009) ([raw file](https://github.com/w3c/wpt-tools/blob/abde525262acdf6e259bcd9e5faba68a678ef22b/runner/runner.js#L119)):*
<details><summary><i>Previously, sideshowbarker (Michael[tm] Smith) wrote…</i></summary>
> I think emitting a warning should be sufficient for now</details>
Done.

---

*[runner/runner.js, line 427 \[r2\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KH3AdIJtwA-WFexb9B4:-KHKdL11cENXDDzr3Jzy:-499146009) ([raw file](https://github.com/w3c/wpt-tools/blob/5adbbda1559a8fdc450946e6b5fffe262eea7a4c/runner/runner.js#L427)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Also, mention that we are only presenting the first.</details>
Done.

---

*[runner/runner.js, line 53 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZ9ol6SUzj99vPmFb:-KHKdF5nUlhm60tNN5Bo:5173157) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L53)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> `var`</details>
??

---

*[runner/runner.js, line 62 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZlxJ1VhVl_55hyu0:-KHKcpyHaPwLd142r4OK:-946327141) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L62)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> This `[0]` isn't really right; it should be all items (a single test file can have multiple variants that contribute different tests). Also you need to consider deleted items and the fact that reftests can change what their reference is, or whatever.
> 
> Unfortunately the best way to do this is probably to look at how the python code works and emulate that behaviour.</details>
Can I cry now?  I will trawl through that code.  Can I assume that the purpose of this is to support  changes that would override the   associated github repo?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[runner/runner.js, line 62 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZlxJ1VhVl_55hyu0:-KHNZdBv_5ys5-v1wAam:-822913376) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L62)):*
<details><summary><i>Previously, halindrome (Shane McCarron) wrote…</i></summary>
> Can I cry now?  I will trawl through that code.  Can I assume that the purpose of this is to support  changes that would override the   associated github repo?</details>
Actually, having had a troll through the code now... I confess to being mystified about what problem it is trying to solve.  It looks at git to see if files are deleted ? As in someone marked this as deleted but has not yet done a commit so that it would actually go away?  That's just weird.  I am not sure what to do with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
@sideshowbarker @jgraham curious what I can do to get this kicked loose.  We have some work hanging fire that depends on it.

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[runner/runner.js, line 62 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZlxJ1VhVl_55hyu0:-KJf7hQUCUTlaJ3Sya1D:-1040706400) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L62)):*
<details><summary><i>Previously, halindrome (Shane McCarron) wrote…</i></summary>
> Actually, having had a troll through the code now... I confess to being mystified about what problem it is trying to solve.  It looks at git to see if files are deleted ? As in someone marked this as deleted but has not yet done a commit so that it would actually go away?  That's just weird.  I am not sure what to do with that.
</details>
Well it's for cases where the file has been deleted, but that delete has not yet been committed to the wpt repository. For example in the Mozilla system, the `local_changes` section contains all the changes that people have made in m-c that have not yet been upstreamed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[runner/runner.js, line 53 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KHKZ9ol6SUzj99vPmFb:-KI2vjFH6enBPglQ5YDw:1458935565) ([raw file](https://github.com/w3c/wpt-tools/blob/0027182129c99dcfffb2981d70cbabac1fc0cd9d/runner/runner.js#L53)):*
<details><summary><i>Previously, halindrome (Shane McCarron) wrote…</i></summary>
> ??
</details>
@jgraham you said "var" - do you remember why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/runner.js, line 70 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpa37zVjc3q3qz-MPR:-KJpa37zVjc3q3qz-MPS:250519957) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L70)):*
> ```JavaScript
>             // remove any items that are locally deleted but not yet committed
>             if (ret.length && local.hasOwnProperty("deleted") && local.deleted.length) {
>                 for (var i = 0; i < local.deleted.length; i++ ) {
> ```

I wonder if it's faster to make an object like
`var deleted = {}
local.deleted.each(function(x) {deleted[x] = true})`

and then just iterate over `ret` once checking if each item is in `deleted`.

---

*[runner/runner.js, line 81 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpaZooG-NGfDNDpRnt:-KJpaZop2SKWw80mvIF9:747927489) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L81)):*
> ```JavaScript
>             // remove any items that are ref tests and are locally deleted but 
>             // not yet committed
>             if (ret.length && local.hasOwnProperty("deleted_reftests") && Object.keys(local.deleted_reftests).length > 0 ) {
> ```

Similar efficiency concern. Also, I think you want to check that we have a reftest in this case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/runner.js, line 70 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpa37zVjc3q3qz-MPR:-KJpc6MWFfJr2574Omtu:-1094058397) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L70)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I wonder if it's faster to make an object like
> `var deleted = {}
> local.deleted.each(function(x) {deleted[x] = true})`
> 
> and then just iterate over `ret` once checking if each item is in `deleted`.
</details>
Yeah - I considered that.  My assumption was that in the normal case there are almost none of these.  But I can make this change.

---

*[runner/runner.js, line 81 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpaZooG-NGfDNDpRnt:-KJpcL_FPszPGpDo-nYq:-62594674) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L81)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Similar efficiency concern. Also, I think you want to check that we have a reftest in this case.
</details>
Do you mean that the type is "reftest"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/runner.js, line 81 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpaZooG-NGfDNDpRnt:-KJpeRJarpB3jiCPdHDO:677251276) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L81)):*
<details><summary><i>Previously, halindrome (Shane McCarron) wrote…</i></summary>
> Do you mean that the type is "reftest"?
</details>
Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by halindrome** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[runner/runner.js, line 70 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpa37zVjc3q3qz-MPR:-KJprDYF_9J4y5jMtrXE:-499146009) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L70)):*
<details><summary><i>Previously, halindrome (Shane McCarron) wrote…</i></summary>
> Yeah - I considered that.  My assumption was that in the normal case there are almost none of these.  But I can make this change.
</details>
Done.

---

*[runner/runner.js, line 81 \[r6\]](https://reviewable.io:443/reviews/w3c/wpt-tools/67#-KJpaZooG-NGfDNDpRnt:-KJprEm5y0DU9YJt9Rl5:-499146009) ([raw file](https://github.com/w3c/wpt-tools/blob/e02d8c236fceddec659dc03ea79fe109a7412a79/runner/runner.js#L81)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Yes.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/67)*

**Pull request merged**
