### PR TITLE
Support python 3 for the code used by wpt's ./lint tool.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/44)

### CODE REVIEW

**Comment by gsnedders** [comment]
@Ms2ger this is obsolete now, right?

**Comment by Ms2ger** [comment]
There's still a lot of bytes/strings confusion, both around paths and file contents

**Comment by gsnedders** [comment]
Can you revisit this now #113 has landed?

**Comment by Ms2ger** [comment]
There's one remaining change, about which I believe you made the following comment:

> Is this not going to implicitly encode on Py2 now?

I don't know the answer to that.

**Comment by gsnedders** [comment]
It… shouldn't? I'm pretty sure I was just being an idiot. :)

**Comment by Ms2ger** [comment]
I'd be happy to land it, then, though I'd probably not complain if you asked to write a test for it :)

**Comment by gsnedders** [comment]
@Ms2ger r?

**Comment by gsnedders** [comment]
#170 makes this obsolete.

**Pull request closed without merging**
