### PR TITLE
Refactor and test lint.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/94)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please don't squash on merging.

**Comment by gsnedders** [comment]
*[lint/lint.py, line 327 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/94#-KOB40waIdpT1jbIz4T3:-KOB40wbCNYU7x2K3Tq1:-2062441885) ([raw file](https://github.com/w3c/wpt-tools/blob/52858686b2bee20b793b558689de426e0ff7c3bb/lint/lint.py#L327)):*
> ```Python
>         output_errors = output_errors_text
> 
>     def process_errors(path, errors, last):
> ```

Can we document what the args are here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/94)*

**Comment by gsnedders** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[lint/lint.py, line 281 \[r3\]](https://reviewable.io:443/reviews/w3c/wpt-tools/94#-KOB4uU6F-NYqBQ1kL1_:-KOB4uU6F-NYqBQ1kL1a:965719874) ([raw file](https://github.com/w3c/wpt-tools/blob/ec104ee55ee36ac7d9c8e89296dec84318a769ab/lint/lint.py#L281)):*
> ```Python
> def check_file_contents(repo_root, path, f):
>     errors = []
>     for file_fn in [check_regexp_line, check_parsed, check_python_ast]:
> ```

Can we keep these in `file_lints`? I somewhat dislike hardcoding this list in the middle of a function.

---

*[lint/lint.py, line 281 \[r4\]](https://reviewable.io:443/reviews/w3c/wpt-tools/94#-KOB6bs95IVwJqSo3wrf:-KOB6bsAs_reVO2T4a2R:-1240207398) ([raw file](https://github.com/w3c/wpt-tools/blob/84480f3653e2fc9a4df360b40508b29b54ca1288/lint/lint.py#L281)):*
> ```Python
> def check_path(repo_root, path):
>     errors = []
>     for path_fn in [check_path_length]:
> ```

Similarly, keep these in `path_lints`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/94)*

**Comment by gsnedders** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r13.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/94#-:-KOBLWr8HWlfeaprOzqT:1417088721)*

**Pull request merged**
