### PR TITLE
Manifest v4 change fixes

### LINKED ISSUE #144: Fix the test runner
After the manifest changes in #125 and #90 landed, the runner broke. We should fix this before updating the tools submodule in wpt.

### PR DESCRIPTION
**Pull request by jeremypoulter**
Changes to update the test runner to support the new style manifest, resolves #144.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/147)

### CODE REVIEW

**Comment by gsnedders** [comment]
Small nit: we seem to otherwise use a space after keyword before the `(`, so it should probably be consistent with that.

Otherwise: this is great! It's exactly what we need for #144 and means I don't need to get my head around runner.js again. :)

**Comment by jgraham** [comment]
@jeremypoulter Thanks!

**Comment by jeremypoulter** [comment]
Made those changes.

**Comment by gsnedders** [comment]
@jeremypoulter Thanks for doing all this!

**Pull request merged**
