### PR TITLE
Support setting timeouts for worker tests.

### PR DESCRIPTION
**Pull request by Ms2ger**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/156)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Alternative for #76

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[manifest/sourcefile.py, line 19 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/156#-Kbz9-gJdKUgLduL4JrQ:-Kbz9-gJdKUgLduL4JrR:b9tbri7) ([raw file](https://github.com/w3c/wpt-tools/blob/795afb915a4ff3ed4eab7e1d26e60f5893b59944/manifest/sourcefile.py#L19)):*
> ```Python
> 
> wd_pattern = "*.py"
> meta_re = re.compile(b"//\s*META:\s*(\w*)=(.*)$")
> ```

Make this match the start of the line.

---

*[manifest/sourcefile.py, line 39 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/156#-Kbz943HNt5gBJGfxsHK:-Kbz943HNt5gBJGfxsHL:b-iqf6y9) ([raw file](https://github.com/w3c/wpt-tools/blob/795afb915a4ff3ed4eab7e1d26e60f5893b59944/manifest/sourcefile.py#L39)):*
> ```Python
>     for line in f:
>         assert isinstance(line, binary_type), line
>         m = meta_re.match(line)
> ```

Maybe force these to be the first lines in the file.

---

*[manifest/tests/test_sourcefile.py, line 188 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/156#-Kbz791DVAJcINDSendH:-Kbz791EAoNjocNmPiaY:b-xk66sz) ([raw file](https://github.com/w3c/wpt-tools/blob/795afb915a4ff3ed4eab7e1d26e60f5893b59944/manifest/tests/test_sourcefile.py#L188)):*
> ```Python
> test()"""
> 
>     metadata = read_script_metadata(BytesIO(contents))
> ```

This seems to be unused?

---

*[serve/serve.py, line 71 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/156#-Kbz7LdANj7DkZKtblKU:-Kbz7LdANj7DkZKtblKV:b-oac85x) ([raw file](https://github.com/w3c/wpt-tools/blob/795afb915a4ff3ed4eab7e1d26e60f5893b59944/serve/serve.py#L71)):*
> ```Python
>                         yield '<meta name="timeout" content="long">'
>                 else:
>                     raise ValueError("Unexpected metadata")
> ```

I don't think this is a good idea. A lint would be better.

---

*[serve/serve.py, line 111 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/156#-Kbz9xgnoFDgUoq49DwL:-Kbz9xgnoFDgUoq49DwM:b-yxn4ah) ([raw file](https://github.com/w3c/wpt-tools/blob/795afb915a4ff3ed4eab7e1d26e60f5893b59944/serve/serve.py#L111)):*
> ```Python
>                         yield '<meta name="timeout" content="long">'
>                 else:
>                     raise ValueError("Unexpected metadata")
> ```

+1 bad idea

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/156)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/156)*

**Comment by Ms2ger** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[manifest/sourcefile.py, line 19 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/156#-Kbz9-gJdKUgLduL4JrQ:-KbzUtb6pmd2KJ1RSvJo:b-nv8kmp) ([raw file](https://github.com/w3c/wpt-tools/blob/795afb915a4ff3ed4eab7e1d26e60f5893b59944/manifest/sourcefile.py#L19)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Make this match the start of the line.
</blockquote></details>

`re.match` already checks that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/156)*

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r4, 1 of 1 files at r5.
Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/156)*

**Pull request merged**
