### PR TITLE
Spec version testcases

### PR DESCRIPTION
**Pull request by maxpassion**
Extension to show the spec version of each test case

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/72)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Please explain why this is useful and where you would use this.

**Comment by maxpassion** [comment]
This is an optional feature to enable a test case author to include the specification version information of the test by inserting a meta tag. 

For example, the test case author can include the following meta information to indicate that this test case is one of the test cases for HTML5.1 specification: 
<meta name="spec_version" content="5.1"  />

The test result pages will show the specification version information accordingly.

Further work is needed to make this feature optional and easy to use. (For example, add a selection box to select the version number and disable/enable this feature in the page of index.html).

**Comment by Ms2ger** [comment]
We only write tests for the latest version of a specification; git branches are used for snapshotting if needed. (It has never been needed so far.)

**Comment by maxpassion** [comment]
Since there are some test cases not related to any W3C released standards, this optional feature could be useful sometimes. 

For example, if some one wants to know the compatibility with the latest W3C released standards(e.g. HTML5.1), they may want to run the test cases that related to HTML5.1 spec and not run the test cases that not related to any W3C released standards.

**Comment by sideshowbarker** [comment]
> We only write tests for the latest version of a specification; git branches are used for snapshotting if needed. (It has never been needed so far.)

I think it is useful to at least discuss providing an option in the web runner for this for others who want to use it—as long as it’s completely optional and doesn’t create any additional work for test contributors or maintainers. So I ask that we leave this open until we can have a little more discussion and get final agreement about whether to accept this patch or not.

**Comment by RByers** [comment]
Often the convenient thing to do from one version of a spec to another is to change existing tests (eg. remove tests for deprecated fields).  Trying to maintain the tests for all versions of a spec in the same set of files would be an engineering nightmare.

Instead I agree with @Ms2ger that we should rely on branches / tags that snapshot the tests at a particular point in time (just like we snapshot/branch specs).

**Comment by jgraham** [comment]
I saw the discussions at TPAC on this topic and based on what was presented there I feel:

* This does not, and cannot, solve the original use case that was set out. As I understand it, the idea is to give developers an indication of what's compatibly implemented in browsers of various ages. However since browsers do not in general target complete implementation of a specific spec version before moving on to complete implementation of the next spec version, recording the version number associated with a test doesn't provide any value to web developers. Instead they need to see which subfeatures of each spec are supported in each browser; this is what services like caniuse.com attempt to provide (albeit in an incomplete way).

* This does not provide value to implementors. In general implementors look at the latest version of a spec, and there would be value to them in knowing that the spec and tests had diverged in some way. Annotating the tests with references to the particular spec text is often suggested as a solution to that problem; that is much more finegrained than what is suggested here. But note that such annotations also have issues; they tend to become outdated for reasons that do not correspond to the tests being invalidated, and therefore it takes significant initial and ongoing effort to maintain the annotations.

* Merging this would cause non-trivial ongoing maintenance costs both in terms of retaining support in the actual software tools and in terms of informing users that annotations are not required. We are not exactly resource-rich here and I don't want to bear that cost.

So in general I don't support merging this. I think if, despite the ongoing objections, you wish to work on this feature, you should do it using out-of-repository metadata (e.g. a json file mapping test path to spec versions) and a fork of the runner. But I very much recommend that you reconsider the solution that you are using, because I think your goal is very sensible, but that this will not work to achieve it.

**Pull request closed without merging**
