### PR TITLE
Manifest hash

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/125)

### CODE REVIEW

**Comment by gsnedders** [comment]
*[manifest/manifest.py, line 120 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTP__tSgDnbd6cEXxXp:-KTP__tSgDnbd6cEXxXq:b2pvrhp) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L120)):*
> ```Python
> 
>         for item in reftest_nodes:
>             # This is proabably not great for pypy...
> ```

Ewww ewww ewww ewwwwwwww. Plz no.

So, uh, what? We end up with `self._data["reftest"].values()` being a iterator of lists of test items, some of which are `RefTest` objects and some of which are `RefTestNode` objects? That seems like a really awkward way of getting the list of source nodes. Instead of all of this mess, can we not just have a separate list of source nodes, as we had before?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Reviewed 9 of 11 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[manifest/manifest.py, line 74 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPUhN2JqiuiP3hcIvI:-KTPUhN2JqiuiP3hcIvJ:b-90wsbd) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L74)):*
> ```Python
>                 content = tree.show_file(rel_path)
> 
>             source_file = SourceFile(tests_root,
> ```

I dislike that you've done away with `add`; it makes unit testing of the class much harder (as we now have to construct something that quacks like a `tree`). Can we have an `add` which takes a `SourceFile` as its argument?

---

*[manifest/manifest.py, line 131 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPi1ve7IelyoczsIih:-KTPi1ve7IelyoczsIii:b-rt1xt8) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L131)):*
> ```Python
>         out_items = {
>             test_type: {
>                 to_os_path(path):
> ```

Where does that path get converted from the OS path? I can't work out why that isn't an OS path in `self._data`?

---

*[manifest/sourcefile.py, line 135 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPervkqFXROjLC_wmp:-KTPervkqFXROjLC_wmq:binipfa) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/sourcefile.py#L135)):*
> ```Python
> 
>     @property
>     def name_is_conformance(self):
> ```

This and the `_support` variant below cause a few tests to fail. Plz make them pass.

---

*[manifest/update.py, line 14 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPj37ui0ANXQNBEYW9:-KTPj37vIFtKOeUmmJj8:b-2v4lza) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/update.py#L14)):*
> ```Python
> 
> 
> def profile(f):
> ```

In general I'm against any such profile decorators, especially when they're just applied to basically the top-level function of the program. `cProfile` and `vmprof` both offer better ways to profile entire programs.

---

*[manifest/update.py, line 23 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPitLLWKKMOoGAetS8:-KTPitLLWKKMOoGAetS9:bh9u2ro) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/update.py#L23)):*
> ```Python
>         finally:
>             p.disable()
>             p.dump_stats("profile.out")
> ```

Regardless, can we not write out random files in the cwd?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
*[a discussion](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPoqIYIl649HGy5h8i:-KTPoqIYIl649HGy5h8j:b-59pndh) (no related file):*
Also: fix tests and flakes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Review status: 10 of 15 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[manifest/manifest.py, line 74 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPUhN2JqiuiP3hcIvI:-KTR26LfcbEyL1Nk2LQQ:b-lw72rc) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L74)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> I dislike that you've done away with `add`; it makes unit testing of the class much harder (as we now have to construct something that quacks like a `tree`). Can we have an `add` which takes a `SourceFile` as its argument?
</details>
No, no `add` method. The manifest is explicitly immutable except from the `update` method that overwrites it. I refactored a bit so you can easily pass a list of `SourceFile` objects to update for test purposes.

---

*[manifest/manifest.py, line 120 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTP__tSgDnbd6cEXxXp:-KTR2lLsRbt37SgxKMyc:b-dugcxb) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L120)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> Ewww ewww ewww ewwwwwwww. Plz no.
> 
> So, uh, what? We end up with `self._data["reftest"].values()` being a iterator of lists of test items, some of which are `RefTest` objects and some of which are `RefTestNode` objects? That seems like a really awkward way of getting the list of source nodes. Instead of all of this mess, can we not just have a separate list of source nodes, as we had before?
</details>
I totally don't think my replacement is actually a meaningful improvement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[manifest/manifest.py, line 120 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTP__tSgDnbd6cEXxXp:-KTUYraHT2cSUkSQj0sO:b-8r8x5) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L120)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> I totally don't think my replacement is actually a meaningful improvement.
</details>
@Ms2ger, opinions?

---

*[manifest/manifest.py, line 140 at r3](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTUYbttHy3m0Bc3a5fP:-KTUYbttHy3m0Bc3a5fQ:b9ux0mo) ([raw file](https://github.com/w3c/wpt-tools/blob/ef2c1666f805dc1c41232b6698d8be1736b3ed47/manifest/manifest.py#L140)):*
> ```Python
>                                    item.manifest)
>                 reftests[item.source_file.rel_path].append(item)
>                 if item.__class__ == RefTestNode:
> ```

This branch is never taken and should be deleted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Reviewed 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
*[manifest/manifest.py, line 120 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTP__tSgDnbd6cEXxXp:-KWmeMwwDgnZnc6TT1bn:b-ivgspx) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L120)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> @Ms2ger, opinions?
</details>
@Ms2ger: ping

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: 12 of 15 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[manifest/sourcefile.py, line 135 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPervkqFXROjLC_wmp:-KWnSB8pKLN-zohhAEuk:bkcykm8) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/sourcefile.py#L135)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> This and the `_support` variant below cause a few tests to fail. Plz make them pass.
</details>
They now pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
OK, so 9ab7cd5 passed on Linux (some Windows bug, path separator related), but the following commit adds a failing test (we don't recompute reftests when a test is deleted).

**Comment by Ms2ger** [comment]
Ping me on IRC second half of next week if you still need my review.

**Comment by gsnedders** [comment]
Also: we *really* ought document MANIFEST.json's structure for people wanting to implement runners on top of it.

**Comment by gsnedders** [comment]
Status: seemingly working on Linux, one Windows bug remaining (see my above review comment), and in dire need of documentation.

**Comment by gsnedders** [comment]
*[manifest/update.py, line 23 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPitLLWKKMOoGAetS8:-KX76tJPATP0QVEdBRuF:bb6ywmx) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/update.py#L23)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> Regardless, can we not write out random files in the cwd?
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: 10 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPoqIYIl649HGy5h8i:-KX7NpLhXn69ukS2DpNs:bb6ywmx) (no related file):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> Also: fix tests and flakes.
</details>
LGTM

---

*[manifest/manifest.py, line 120 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTP__tSgDnbd6cEXxXp:-KX7O-T0XkljLYfDh52z:b-2xye1t) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L120)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> @Ms2ger: ping
</details>
So what I want opinions on is `to_RefTestNode` and `to_RefTest` which are now in item.py

---

*[manifest/manifest.py, line 131 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTPi1ve7IelyoczsIih:-KX7NscXEqRPfw62E5oU:b-n4nyv) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L131)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> Where does that path get converted from the OS path? I can't work out why that isn't an OS path in `self._data`?
</details>
Now fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
@jgraham @Ms2ger r?

**Comment by jgraham** [comment]
Reviewed 5 of 11 files at r1, 3 of 6 files at r2, 1 of 5 files at r3, 1 of 3 files at r4, 9 of 11 files at r6.
Review status: 19 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[conftest.py, line 14 at r6](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXCCoA9aoERoPOxq7o-:-KXCCoAAEUxzbNl-7qrI:b3rz4yr) ([raw file](https://github.com/w3c/wpt-tools/blob/8f90de4dec5cc26ab9b4d1fe9ef4f6da994dcff4/conftest.py#L14)):*
> ```Python
> 
> settings.load_profile(os.getenv("HYPOTHESIS_PROFILE",
>                             "default" if impl != "PyPy" else "pypy"))
> ```

Wacky indentation.

---

*[manifest/manifest.py, line 196 at r6](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXCOAB84Cr7LCKSN8LL:-KXCOABAYgpl9xesgPVn:b-zgfl0l) ([raw file](https://github.com/w3c/wpt-tools/blob/8f90de4dec5cc26ab9b4d1fe9ef4f6da994dcff4/manifest/manifest.py#L196)):*
> ```Python
>                     manifest_item = test_cls.from_json(self,
>                                                        tests_root,
>                                                        path,
> ```

Do we end up calling `to_os_path` twice? Not harmful but also not necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: 17 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[conftest.py, line 14 at r6](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXCCoA9aoERoPOxq7o-:-KXGsZQKK6QRzIX_R9Cn:bt2vr1b) ([raw file](https://github.com/w3c/wpt-tools/blob/8f90de4dec5cc26ab9b4d1fe9ef4f6da994dcff4/conftest.py#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Wacky indentation.
</details>
Fixed.

---

*[manifest/manifest.py, line 196 at r6](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXCOAB84Cr7LCKSN8LL:-KXGsR_lnfCc-eTrxWOG:bt2vr1b) ([raw file](https://github.com/w3c/wpt-tools/blob/8f90de4dec5cc26ab9b4d1fe9ef4f6da994dcff4/manifest/manifest.py#L196)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Do we end up calling `to_os_path` twice? Not harmful but also not necessary.
</details>
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Reviewed 2 of 11 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[manifest/manifest.py, line 120 at r2](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KTP__tSgDnbd6cEXxXp:-KXGsrhV2E-zNsB7G9WN:b-l7da53) ([raw file](https://github.com/w3c/wpt-tools/blob/5fdad283a0da3a52b88a7985d28f080e4619a693/manifest/manifest.py#L120)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> So what I want opinions on is `to_RefTestNode` and `to_RefTest` which are now in item.py
</details>
I mean I don't love messing with `__dict__`; it seems more or less as bad as the original implementation here. But also, I think it works.

---

*[manifest/tests/test_manifest.py, line 24 at r6](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXCWon6ss7KnSeFGTt0:-KXCWon6ss7KnSeFGTt1:b-51r3ug) ([raw file](https://github.com/w3c/wpt-tools/blob/8f90de4dec5cc26ab9b4d1fe9ef4f6da994dcff4/manifest/tests/test_manifest.py#L24)):*
> ```Python
> def rel_dir_file_path(draw):
>     length = draw(hs.integers(min_value=1, max_value=20))
>     if length == 1:
> ```

    if length <= 2:
         return "a" * length

---

*[manifest/tests/test_manifest.py, line 26 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXGu2C0mk3ZaqgVelH8:-KXGu2C0mk3ZaqgVelH9:b-6gx09i) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L26)):*
> ```Python
>     if length == 1:
>         return "a"
>     elif length == 2:
> ```

Does `length=2` actually need a special case i.e. does `draw` not work with zero sizes?

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXHHtWbtziF3HBuC1Bt:b-us15kh) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
> ```Python
>     assert m.update([s]) is True
> 
>     if platform.system() == "Windows":
> ```

Wait, what? The manifest should be platform-independent, right? Basically I think this case shouldn't be possible on linux and we should try to throw in the case where it would happen (because we are calling `to_os_path` on a string containing a `\`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[manifest/tests/test_manifest.py, line 26 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXGu2C0mk3ZaqgVelH8:-KXHOCfzqwGFAnVCNXgx:b-fi0icg) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L26)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Does `length=2` actually need a special case i.e. does `draw` not work with zero sizes?
</details>
Uh, it seems to work with zero. Though that's a bit weird. Guess we can do that.

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXHNxqCNqJS4W7NM_Dv:bkce7p3) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> Wait, what? The manifest should be platform-independent, right? Basically I think this case shouldn't be possible on linux and we should try to throw in the case where it would happen (because we are calling `to_os_path` on a string containing a `\`.
</details>
How? if `os.path.sep == '/'` disallow `\`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
*[manifest/tests/test_manifest.py, line 24 at r6](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXCWon6ss7KnSeFGTt0:-KXHPB3S0BhZZV3B46i9:b-giah3b) ([raw file](https://github.com/w3c/wpt-tools/blob/8f90de4dec5cc26ab9b4d1fe9ef4f6da994dcff4/manifest/tests/test_manifest.py#L24)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
>     if length <= 2:
>          return "a" * length
</details>
LGTM; the middle branch is gone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Review status: 19 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXHOxiDRK9yHpM-zcQo:b-5kx2ym) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> How? if `os.path.sep == '/'` disallow `\`?
</details>
If the input to `to_os_path` or the output from `from_os_path` contains a `\` then throw, independent of the separator. That doesn't stop you constructing an invalid object via the internals, but it does mean you can't serialize it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: 19 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXHPQGS4wv_LdzNP8Jy:bp8i1ax) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> If the input to `to_os_path` or the output from `from_os_path` contains a `\` then throw, independent of the separator. That doesn't stop you constructing an invalid object via the internals, but it does mean you can't serialize it.
</details>
But Windows OS paths will contain a `\`, hence we can't do that in `from_os_path`, surely?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[manifest/utils.py, line 14 at r10](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHVm4ZIh46I6dyF-Fl:-KXHVm4_RjBvxyHPdTrC:b-2fjzw6) ([raw file](https://github.com/w3c/wpt-tools/blob/ee555e5d9739e9b96e451397df1fb3432e6538f7/manifest/utils.py#L14)):*
> ```Python
> 
> def from_os_path(path):
>     if os.path.sep == "/" and "\\" in path:
> ```

No, like this
    rv = path.replace(os.path.sep, "/")
    if "\\" in rv:
        raise ValueError([…])
    return rv

---

*[manifest/utils.py, line 20 at r10](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHW3eP6D7DUAwM89nU:-KXHW3eP6D7DUAwM89nV:b-mv0ku8) ([raw file](https://github.com/w3c/wpt-tools/blob/ee555e5d9739e9b96e451397df1fb3432e6538f7/manifest/utils.py#L20)):*
> ```Python
> 
> def to_os_path(path):
>     return path.replace("/", os.path.sep)
> ```

This should also raise ValueError if the input contains a `\`

---

*[manifest/tests/test_manifest.py, line 120 at r10](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHWITLLWu78vd9xeC0:-KXHWITLLWu78vd9xeC1:b-7hutn3) ([raw file](https://github.com/w3c/wpt-tools/blob/ee555e5d9739e9b96e451397df1fb3432e6538f7/manifest/tests/test_manifest.py#L120)):*
> ```Python
> 
> 
> @pytest.mark.skipif(os.path.sep != "\\",
> ```

So I think this is still wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: 19 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[manifest/utils.py, line 14 at r10](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHVm4ZIh46I6dyF-Fl:-KXMBFLxKOoRVDlO15Kv:b-laqwt7) ([raw file](https://github.com/w3c/wpt-tools/blob/ee555e5d9739e9b96e451397df1fb3432e6538f7/manifest/utils.py#L14)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> No, like this
>     rv = path.replace(os.path.sep, "/")
>     if "\\" in rv:
>         raise ValueError([…])
>     return rv
</details>
Is there any reason why that is preferable?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by Ms2ger** [comment]
Can we have a file that explains the structure of the manifest?

**Comment by gsnedders** [comment]
@Ms2ger I was just trying to land this quickly because @qyearsley was going to start implementing stuff on top of this and then do documentation soon thereafter. I can do it first, if you insist. :)

**Comment by jgraham** [comment]
Reviewed 1 of 2 files at r11.
Review status: 20 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[manifest/utils.py, line 14 at r10](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHVm4ZIh46I6dyF-Fl:-KXNCdvO_hXAgS-vcABP:b-xmg5i9) ([raw file](https://github.com/w3c/wpt-tools/blob/ee555e5d9739e9b96e451397df1fb3432e6538f7/manifest/utils.py#L14)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> Is there any reason why that is preferable?
</details>
Yes, because it doesn't involve system-specific code, it just checks the invariant in all cases without worrying about what should or should not be possible.

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXNCsdfmrijdEBK4UxG:bc1nfqp) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> But Windows OS paths will contain a `\`, hence we can't do that in `from_os_path`, surely?
</details>
The output from `from_os_path` is by definition not os-specific and in particular never contains a `\`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by gsnedders** [comment]
Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXNGS7BQKg3vbCbh7Ju:bwd9cwm) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
<details><summary><i>Previously, jgraham wrote…</i></summary>
> The output from `from_os_path` is by definition not os-specific and in particular never contains a `\`.
</details>
Fine. But the still has different behaviour between platforms because the same input value can return `ValueError` on `os.path.sep == '/'` and something meaningful with `os.path.sep == '\\'` hence why we still have the pytest.mark.skipif. I can make it explicitly test that it throws if you prefer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manifest/utils.py, line 22 at r12](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXQuUSAE1H1AP3wSNE2:-KXQuUSAE1H1AP3wSNE3:blbqy0j) ([raw file](https://github.com/w3c/wpt-tools/blob/99dfd3ba0502865827dec5639849abc75c43fc25/manifest/utils.py#L22)):*
> ```Python
> def to_os_path(path):
>     if "\\" in path:
>         raise ValueError("URL contains \\")
> ```

That's not a URL.

---

*[manifest/tests/test_manifest.py, line 123 at r7](https://reviewable.io:443/reviews/w3c/wpt-tools/125#-KXHHtWadJOfLwAorbzT:-KXQugi4926zNqDh6V5K:b-vj2c8r) ([raw file](https://github.com/w3c/wpt-tools/blob/471d3fa74bae7f41551e645597189fb9c7a82517/manifest/tests/test_manifest.py#L123)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary>
> Fine. But the still has different behaviour between platforms because the same input value can return `ValueError` on `os.path.sep == '/'` and something meaningful with `os.path.sep == '\\'` hence why we still have the pytest.mark.skipif. I can make it explicitly test that it throws if you prefer?
</details>
Yeah, I guess that would be best.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/125)*

**Pull request merged**
