### PR TITLE
Lint for filename duplicates in CSS testsuite

### PR DESCRIPTION
**Pull request by gsnedders**
Does exactly what it says on the tin.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/180)

### CODE REVIEW

**Comment by gsnedders** [comment]
To answer the obvious review comments:

Yes, this approach is asymptotically suboptimal, but a better approach reusing where we've already parsed the files would end up with gratuitous memory usage as we wouldn't know what would be dupes at that stage (and potentially end up being slower than eating the cost reparsing a few). It also would be far more invasive with our current code and when we want to drop it in a few months that's not worth it.

**Comment by jgraham** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[lint/lint.py, line 51 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KecYMYtc4vm13urgCGP:-KecYMYtc4vm13urgCGQ:b-mnk1y6) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L51)):*
> ```Python
> 
> 
> def _all_files_equal(paths):
> ```

Docstring, please

---

*[lint/lint.py, line 66 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedhLVo0JzzUnBajuv4:-KedhLVqZFWyMNDR0LyI:b-hex6cp) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L66)):*
> ```Python
>         it = iter(range(0, len(paths), groupsize))
>         start = next(it)
>         while start is not None:
> ```

Isn't this just 

    for start in xrange(0, len(paths), groupsize):
        path_group = paths[start:start + groupsize]

---

*[lint/lint.py, line 67 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-Kedi5os07ijWbOCco1K:-Kedi5otFQpG1BP5i3n2:bu2wn0s) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L67)):*
> ```Python
>         start = next(it)
>         while start is not None:
>             first_f.seek(0)
> ```

Rereading `first_f` each time vs just caching it doesn't seem that useful?

---

*[lint/lint.py, line 72 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedheulU36BIx40CaXC:-KedheulU36BIx40CaXD:b-7lnr69) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L72)):*
> ```Python
>             start = end
>             try:
>                 files = [open(x, "rb") for x in path_group]
> ```

This weird scheme of reading 8kB of each file in groups of 8 needs some explanation. I assume it's a perf optimisation, but document why.

---

*[lint/lint.py, line 110 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehSFXqudowlOMA7oX_:-KehSFXrc4MX8ZDxP7Ed:b-va8581) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L110)):*
> ```Python
> 
> 
> def check_css_globally_unique(repo_root, paths, css_mode):
> ```

Document the rules you are trying to enforce here.

---

*[lint/lint.py, line 117 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KediVixlHWmgK5q5Our:-KediViyzdBrSfuqagHV:b-ayymm7) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L117)):*
> ```Python
>     for path in paths:
>         if not css_mode:
>             if os.name == "nt":
> ```

Should this replacement also happen if `css_mode=True`?

---

*[lint/lint.py, line 127 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-Kedign5HHv7sIDL-4GK:-Kedign63Mtc646SdjPK:b-vtkwbx) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L127)):*
> ```Python
>             offset = path.find("/support/")
>             if offset == -1:
>                 continue
> ```

Why? Should the comment from below move up?t

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-KehHOhxpDky4N5NnAgk:bwademl) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
> ```Python
>             if parts[0] in source_file.root_dir_non_test:
>                 continue
>             elif any(item in source_file.dir_non_test - {"support"} for item in parts):
> ```

Does this actually do anything?

---

*[lint/lint.py, line 136 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehH4sCbH7anJukThEn:-KehH4sDBD1_ezxxFxL1:b-2dphzx) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L136)):*
> ```Python
>                 continue
>             else:
>                 for black_path in source_file.dir_path_non_test:
> ```

Can we call this `non_test_path`

---

*[lint/lint.py, line 142 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHcb_EAyIE1GvSCv-:-KehHcb_EAyIE1GvSCv0:b13odp8) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L142)):*
> ```Python
>             name = path[offset+1:]
>             support_files[name].add(path)
>         elif source_file.name_is_reference:
> ```

I really feel like this ought to just read the manifest rather than recreating lots of the related logic here.

---

*[lint/lint.py, line 164 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehSTbTsq_xnlrPhibI:-KehSTbUe5TzGMqEzZ_x:bqb86pk) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L164)):*
> ```Python
>                         else:
>                             continue
>                         by_spec[spec].add(path)
> ```

What if `spec` is undefined here?

---

*[lint/lint.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehUNXBI0huDdGOqxXS:-KehUNXCgldvtAwJcS02:b-prn4ml) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L167)):*
> ```Python
> 
>                 for spec, paths in iteritems(by_spec):
>                     if not _all_files_equal([os.path.join(repo_root, x) for x in paths]):
> ```

It seems like _all_files_equal could return a hash of the files rather than reading them twice (did I mention the manifest already has this?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[lint/lint.py, line 66 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedhLVo0JzzUnBajuv4:-Kf7BpujaHxOfBOZ9sne:b-ewdhu) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L66)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Isn't this just 

    for start in xrange(0, len(paths), groupsize):
        path_group = paths[start:start + groupsize]
</blockquote></details>

I was about to say no. Maybe it is.

---

*[lint/lint.py, line 67 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-Kedi5os07ijWbOCco1K:-Kf7CkBxZy_GSSgdQln3:btsl4o9) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L67)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Rereading `first_f` each time vs just caching it doesn't seem that useful?
</blockquote></details>

Trying to avoid having to keep the whole file in memory.

---

*[lint/lint.py, line 72 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedheulU36BIx40CaXC:-Kf7DW6wYxU6FC6MMcJ1:bn1tbiv) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L72)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

This weird scheme of reading 8kB of each file in groups of 8 needs some explanation. I assume it's a perf optimisation, but document why.
</blockquote></details>

Don't want to read in overly small chunks or you lose perf; don't want to read in overly large chunks or you eat up all the memory.

Groups of eight is all about trying to avoid taking up too many file descriptors.

---

*[lint/lint.py, line 117 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KediVixlHWmgK5q5Our:-Kf7Do3kFMbb_V947UPn:bb77ufg) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L117)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Should this replacement also happen if `css_mode=True`?
</blockquote></details>

Yes.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf7Tidyjoomo_F7euH6:bihm0nn) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Does this actually do anything?
</blockquote></details>

Yes, it checks that it isn't in resources or tools

---

*[lint/lint.py, line 142 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHcb_EAyIE1GvSCv-:-Kf7TyobZw2iZmHnLCzt:b-8idbhr) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L142)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I really feel like this ought to just read the manifest rather than recreating lots of the related logic here.
</blockquote></details>

We can't just do that, partly because this is genuinely based off of filename rather than the far more computed graph-based file types the manifest ends up with.

---

*[lint/lint.py, line 164 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehSTbTsq_xnlrPhibI:-Kf7ZHHs_e0f-8Mrkst5:b9swr9j) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L164)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

What if `spec` is undefined here?
</blockquote></details>

It can't be, because of the `continue` on the previous line. Non-obvious code-flow, I admit.

---

*[lint/lint.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehUNXBI0huDdGOqxXS:-Kf7ZqmUHWn9vOn4jDy0:b-jepkc7) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L167)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

It seems like _all_files_equal could return a hash of the files rather than reading them twice (did I mention the manifest already has this?).
</blockquote></details>

Honestly, that scarcely seems worth it in terms of extra complexity v. performance.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by gsnedders** [comment]
Review status: 16 of 17 files reviewed at latest revision, 12 unresolved discussions.

---

*[lint/lint.py, line 51 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KecYMYtc4vm13urgCGP:-Kf7bauPb93LHAJu9Tzb:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L51)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Docstring, please
</blockquote></details>

Done.

---

*[lint/lint.py, line 66 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedhLVo0JzzUnBajuv4:-Kf7bc2rbvZ1Sbh8TTvK:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L66)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

I was about to say no. Maybe it is.
</blockquote></details>

Done.

---

*[lint/lint.py, line 110 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehSFXqudowlOMA7oX_:-Kf7bds9ycHKP4dyZ19M:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L110)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Document the rules you are trying to enforce here.
</blockquote></details>

Done.

---

*[lint/lint.py, line 127 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-Kedign5HHv7sIDL-4GK:-Kf7bfGEAP3OAgUXrTvD:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L127)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Why? Should the comment from below move up?t
</blockquote></details>

Done.

---

*[lint/lint.py, line 136 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehH4sCbH7anJukThEn:-Kf7bgQNXppwqpFRPL7k:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L136)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Can we call this `non_test_path`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[lint/lint.py, line 67 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-Kedi5os07ijWbOCco1K:-Kf7dB4ARzAkhQnt5nFi:bacs1sr) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L67)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Trying to avoid having to keep the whole file in memory.
</blockquote></details>

I guess I don't have a strong opinon here, but I wonder why you decided this was the right tradeoff? Do we know if there's a perf difference assuming that we aren't memory constrained.

---

*[lint/lint.py, line 72 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedheulU36BIx40CaXC:-Kf7dRFbL6RhLLmMpf80:b1y2hap) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L72)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Don't want to read in overly small chunks or you lose perf; don't want to read in overly large chunks or you eat up all the memory.

Groups of eight is all about trying to avoid taking up too many file descriptors.
</blockquote></details>

That's fine, but it needs a comment.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf7dyd-tpGxiJdMLuBV:b-t5px52) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Yes, it checks that it isn't in resources or tools
</blockquote></details>

Do we have cases with `/support/resources/` or similar? We already checked that `support` was in the path.

---

*[lint/lint.py, line 142 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHcb_EAyIE1GvSCv-:-Kf7eAiCn2ay2bZ8EP-Z:b-9axdml) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L142)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

We can't just do that, partly because this is genuinely based off of filename rather than the far more computed graph-based file types the manifest ends up with.
</blockquote></details>

OK, I guess.

---

*[lint/lint.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehUNXBI0huDdGOqxXS:-Kf7eMVgvY6-O7x4bc6Y:byj52xh) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L167)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Honestly, that scarcely seems worth it in terms of extra complexity v. performance.
</blockquote></details>

How long does reading all the files take?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[lint/lint.py, line 67 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-Kedi5os07ijWbOCco1K:-Kf7jNfppE3kPzSOtTJk:bzctt8y) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L67)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I guess I don't have a strong opinon here, but I wonder why you decided this was the right tradeoff? Do we know if there's a perf difference assuming that we aren't memory constrained.
</blockquote></details>

The perf is "good enough" with those current trade-offs, so I didn't bother trying too much.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf7io5opX-kyNyhLZkK:b-3wsrb2) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Do we have cases with `/support/resources/` or similar? We already checked that `support` was in the path.
</blockquote></details>

The problem is that we exclude `work-in-progress`, and there's lots of badness contained in there in directories like `work-in-progress/foo/bar/support`.

---

*[lint/lint.py, line 167 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehUNXBI0huDdGOqxXS:-Kf7iz4-GKMwRh87jBnh:b-yoaf3t) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L167)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

How long does reading all the files take?
</blockquote></details>

Well, `_all_files_equal` has 0.005s cumulatively used in it over 178 calls, and 0.001s used internally, so I guess around 0.004s?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf82-_TYwmA368bEhhO:b-talob4) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

The problem is that we exclude `work-in-progress`, and there's lots of badness contained in there in directories like `work-in-progress/foo/bar/support`.
</blockquote></details>

Sorry, I don't quite understand. I assume you want to exclude `work_in_progress`, but I don't understand why this achieves that? DOn't you need to explicitly look at whether `any(parts[1] in item for item in source_file.root_dir_non_test)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by gsnedders** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[lint/lint.py, line 72 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedheulU36BIx40CaXC:-Kf8sQIHWnDDTYX5rWfB:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L72)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

That's fine, but it needs a comment.
</blockquote></details>

Done.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf8mqWP4mkPrOdueupA:b-de5s07) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Sorry, I don't quite understand. I assume you want to exclude `work_in_progress`, but I don't understand why this achieves that? DOn't you need to explicitly look at whether `any(parts[1] in item for item in source_file.root_dir_non_test)`?
</blockquote></details>

This already works. Given a path like `foo/resources/support/bar`, `parts` is `['foo', 'resources', 'support', 'bar']` (uh, given we need a file path!). You know what `for item in parts` does. So we then have `item in source_file.dir_non_test - {'support'}`, which is essentially `item in {'resources', 'tools'}`, which is obviously True for the second item in `parts`.

Note this is pretty literally the code from sourcefile.py with `- {'support'}` added to the vital part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by jgraham** [comment]
Review status: 16 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[lint/lint.py, line 72 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedheulU36BIx40CaXC:-Kf8tsW_6VcHxR-ZzRcf:bspf2ou) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L72)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was hoping for one that explains where the magic number 8 comes from, for example.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf8u1ob9fu-6PVruJZz:b-utb1il) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

This already works. Given a path like `foo/resources/support/bar`, `parts` is `['foo', 'resources', 'support', 'bar']` (uh, given we need a file path!). You know what `for item in parts` does. So we then have `item in source_file.dir_non_test - {'support'}`, which is essentially `item in {'resources', 'tools'}`, which is obviously True for the second item in `parts`.

Note this is pretty literally the code from sourcefile.py with `- {'support'}` added to the vital part.
</blockquote></details>

Right, I understand that. But how is that related to `work-in-progress`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by gsnedders** [comment]
Review status: 16 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[lint/lint.py, line 72 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KedheulU36BIx40CaXC:-Kf8zeSDqVOfAeJrQ9xT:b-896fix) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L72)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I was hoping for one that explains where the magic number 8 comes from, for example.
</blockquote></details>

Done.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-Kf8zf-Wlo6DVaZpQG_c:b-7ztdll) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

Right, I understand that. But how is that related to `work-in-progress`?
</blockquote></details>

That's caught by `parts[0] in source_file.root_dir_non_test` in `css_mode`, or the `else` clause when not (given the changes to sourcefile.py).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by jgraham** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-KfCgkpq5sqX8sNZB50m:b-9k43fw) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

That's caught by `parts[0] in source_file.root_dir_non_test` in `css_mode`, or the `else` clause when not (given the changes to sourcefile.py).
</blockquote></details>

I would still like a comment here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by gsnedders** [comment]
*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-KfChACZ-PSZHyQ72LFu:b-yk7dya) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, jgraham wrote…</i></summary><blockquote>

I would still like a comment here.
</blockquote></details>

Saying what? I don't know what to say that isn't duplicating the above comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by jgraham** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lint/lint.py, line 133 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/180#-KehHOhwrso8dSmgOlN8:-KfCnIaR5iqfRixb1d30:bgj4xw5) ([raw file](https://github.com/w3c/wpt-tools/blob/a33d89449f6321358f0a1514c864833ae0f327f4/lint/lint.py#L133)):*
<details><summary><i>Previously, gsnedders (Geoffrey Sneddon) wrote…</i></summary><blockquote>

Saying what? I don't know what to say that isn't duplicating the above comment.
</blockquote></details>

Something that's clearer about what we are trying to achieve and why. Why do we ignore files that aren't tests unless they're in `support`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/180)*

**Pull request merged**
