### PR TITLE
Support setting metadata e.g. timeouts for worker tests.

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/76)

### CODE REVIEW

**Comment by jgraham** [comment]
@Ms2ger: r?

**Comment by halindrome** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/76)*

**Comment by hallvors** [comment]
So this syntax will be 

```
// <meta> timeout=long
```
?

**Comment by jgraham** [comment]
Yes

**Comment by Ms2ger** [comment]
I'm not happy about the regex living in two places.

**Comment by Ms2ger** [comment]
Landed a similar implementation in #156.

**Pull request closed without merging**
