### PR TITLE
lint for usage of setTimeout

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/5)

### CODE REVIEW

**Comment by sideshowbarker** [comment]
We don’t want to merge this yet, right? Given that the repo has nearly 600 existing instances of `setTimeout` that we’d need to change first.

**Comment by sideshowbarker** [comment]
OK I see this is waiting on https://github.com/w3c/web-platform-tests/pull/1816 to be merged.

**Comment by gsnedders** [comment]
This should probably just land and we should whitelist what's already there, rather than waiting indefinitely for https://github.com/w3c/web-platform-tests/pull/1816 to land.

**Comment by gsnedders** [comment]
@jgraham @Ms2ger @sideshowbarker let's just land this and whitelist what's currently using it rather than waiting for the never-future when w3c/web-platform-tests#1816 is merged.

**Comment by sideshowbarker** [comment]
> let's just land this and whitelist what's currently using it rather than waiting for the never-future when w3c/web-platform-tests#1816 is merged.

OK by me

**Pull request merged**
