### PR TITLE
Implement support for multi-global tests.

### PR DESCRIPTION
**Pull request by Ms2ger**
CC <https://github.com/w3c/web-platform-tests/issues/2558>.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/88)

### CODE REVIEW

**Comment by Ms2ger** [comment]
See https://github.com/w3c/web-platform-tests/commit/3c7cfc6f0e7a4402aea187f8b85281b6e8ee4147 for a working example.

**Comment by jgraham** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[manifest/sourcefile.py, line 307 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/88#-KNaKW3LQyMMjtwip-um:-KNaKW3Mz8vklcLbp16u:2111634982) ([raw file](https://github.com/w3c/wpt-tools/blob/4c32741f5505c50ba79fcaf129cef3d909dd56d0/manifest/sourcefile.py#L307)):*
> ```Python
>         elif self.name_is_multi_global:
>             rv = [
>                 TestharnessTest(self, self.url.replace(".any.js", ".any.html")),
> ```

This seems slightly wrong since it would do something strange to `foo.any.js.any.js`. Which I agree shouldn't exist, but still would be good to just replace the end of the url.

---

*[serve/serve.py, line 54 \[r1\]](https://reviewable.io:443/reviews/w3c/wpt-tools/88#-KNaLeg1jjNkpw0JNINH:-KNaLeg2C2HnD9k5N4VO:1517279860) ([raw file](https://github.com/w3c/wpt-tools/blob/4c32741f5505c50ba79fcaf129cef3d909dd56d0/serve/serve.py#L54)):*
> ```Python
> 
>     def handle_request(self, request, response):
>         test_path = request.url_parts.path.replace(".any.html", ".any.js")
> ```

Similar comment about `.replace` (I know the existing code is also wrong).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/88)*

**Comment by jgraham** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/88)*

**Comment by jgraham** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/88)*

**Pull request merged**
