### PR TITLE
Improve certificate re-generation heuristic

### PR DESCRIPTION
**Pull request by jugglinmike**
In the process of fixing a bug in this logic, I noticed an outstanding "to do" that was somewhat related, so I added a commit to address that, as well.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/165)

### CODE REVIEW

**Comment by jgraham** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[sslutils/openssl.py, line 12 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/165#-Kd5lkJiqpKVQTJCsUvV:-Kd5lkJiqpKVQTJCsUvW:b-o34f39) ([raw file](https://github.com/w3c/wpt-tools/blob/24ca9c2e5d6f4b005ddb3cebf69a1258ca532a4c/sslutils/openssl.py#L12)):*
> ```Python
> # allows certificates to be proactively re-generated in the "buffer" period
> # prior to their exact expiration time.
> CERT_EXPIRY_BUFFER = dict(hours=1)
> ```

I might increase this from one hour, since a complete test run can take several.

---

*[sslutils/openssl.py, line 317 at r1](https://reviewable.io:443/reviews/w3c/wpt-tools/165#-Kd5lt49MevuJIrykudY:-Kd5lt4Bu5KKlloqfD-q:bn11bed) ([raw file](https://github.com/w3c/wpt-tools/blob/24ca9c2e5d6f4b005ddb3cebf69a1258ca532a4c/sslutils/openssl.py#L317)):*
> ```Python
>             # always in terms of UTC, so the current time should be calculated
>             # accordingly.
>             if end_date < datetime.utcnow() + time_buffer:
> ```

Should be `-`, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/165)*

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/165)*

**Comment by jugglinmike** [comment]
> I might increase this from one hour, since a complete test run can take
> several.

Couldn't hurt! I've increased the value to six hours.

> Should be `-`, right?

I think `+` is correct here. Let's say it's currently 9:07, the certificate is
due to expire at 9:33, and the `time_buffer` is 1 hour:

       utcnow() - 1                    utcnow()  end_date          utcnow() + 1
          08:17                         09:07     09:33               10:17
    08:00                         09:00                         10:00

Under these conditions, we'd want to re-generate the certificate. Adding the
offset to the right-hand side of the comparison seems like the correct operation
to produce this behavior:

    end_date < utcnow() == False
    end_date < utcnow() - 1 == False
    end_date < utcnow() + 1 == True

Does that seem right to you?

**Comment by jgraham** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/w3c/wpt-tools/165)*

**Comment by jgraham** [comment]
You are right ofc. I guess I would find `end_date - time_buffer < time.utcnow()` easier to read, but this is correct.

Squash fixup and merge.

**Comment by jugglinmike** [comment]
All set (original commits available at: https://github.com/w3c/wpt-tools/compare/master...bocoup:cert-expiry-orig)

**Comment by jugglinmike** [comment]
Also: thanks for the review!

**Pull request merged**
