### PR TITLE
Import wdclient directly.

### PR DESCRIPTION
**Pull request by jgraham**
This change is [Reviewable](https://reviewable.io/reviews/w3c/wpt-tools/200)

### CODE REVIEW

**Comment by jgraham** [comment]
@gsnedders @jugglinmike 

I did this as a simple subtree merge. If anyone wants some different approach for here (and the other desubmodulification), please say now.

**Comment by jugglinmike** [comment]
The git work seems fine to me. However!

When I was getting started, it was confusing for me to understand that the
Python statement `import webdriver` resulted in the loading of the `wdclient`
module given that [there is a distinct package on Pypy with that
name](https://pypi.python.org/pypi/webdriver/) and that the linkage between
wptrunner and the Python import search path is a little indirect.

I'm not sure what the post-merge state will look like, though. If that `import`
statement will be more direct (maybe something like `import
..tools.webdriver`), then I'm fine with this. Otherwise, I'm wondering if we
can name the subdirectory `wdclient`.

**Comment by jgraham** [comment]
I think it makes sense to make the change with as few modifications as possible to keep everything working and then consider renaming later on (when it will also be easier to test).

**Comment by andreastt** [comment]
@jugglinmike I agree with your sentiment towards import paths. I’m happy to accept changes moving us in that direction.

**Pull request merged**
